# configs/default.yaml

# Riproducibilità e device
seed: 42
device: cuda     # usa GPU

# Training generale (valori di default, usati solo se non fai grid search / Optuna)
n_reps: 1000
epochs: 500
batch: 32
lr: 1e-4

# Iperparametri “statici” del modello siamese / contrastive
siamese:
  lambda_ctr: 1.0
  margin: 0.75
  clip_norm: 2.0
  use_amp: false
  verbose: true
  val_split: 0.2
  update_ite_freq: 3
  warmup_epochs_base: 20
  lambda_reg: 0.1

# Dataset
dataset:
  percentile: 15
  num_workers: 0
  use_proxy_ite: true

# Parametri specifici di BCAUSS
bcauss_params:
  neurons_per_layer: 200
  act_fn: relu
  reg_l2: 0.01
  ratio: 1.0
  use_bce: false
  norm_bal_term: true
  use_targ_term: false
  b_ratio: 1.0
  scale_preds: true
  optim: adam
  learning_rate: 1e-5
  momentum: 0.9
  bs_ratio: 0.1

# —————————————————————
# SEARCH SPACE per Grid Search
grid:
  margin:      [0.75]                           # tieni solo il valore utile
  lambda_ctr:  [1.0]
  lr:          [2e-4, 3e-4, 5e-4, 7e-4, 1e-3]
  batch_size:  [32]

# —————————————————————
# PARAMETRI per Optuna (se usi lo script con Optuna)
optuna:
  n_trials: 30           # numero di trial totali
  sampler:
    name: TPESampler
    seed: 42
  pruner:
    name: MedianPruner
    n_startup_trials: 5
    n_warmup_steps: 1
