seed: 42
device: cuda      # oppure cpu

# training
n_reps: 1000
epochs: 500
batch: 1024
lr: 1e-4

# siamese
lambda_ctr: 1.0
margin: 1.0
clip_norm: 5.0
use_amp: false     # true per mixed precision

# dataset
percentile: 20
num_workers: 0

use_proxy_ite: true          # Valore booleano: true per usare ITE stimati, false altrimenti
warmup_epochs_base: 50        # Intero: Numero di epoche di warmup per BCAUSS (0 per disabilitare)
update_ite_freq: 3